on:
  push:
    branches:
      - main
      - reference/*
      - lectures/*

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: install dependencies
        run: npm ci
      - run: npm test
      - name: Collect coverage for client
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./client/coverage/lcov.info
